Fix VcsSim lognames API
This api was introduced by c9f43c165
"Test daisy chained homogeneous spike instances. (#334)"
where multiple logs were needed.

However, this API was not implemented for VcsSim
so verilated rocket chip wont run, which will complain

    File riscv-tests/debug/testlib.py, line 1145, in run
      self.classSetup()
    File riscv-tests/debug/testlib.py, line 1199, in classSetup
      BaseTest.classSetup(self)
    File riscv-tests/debug/testlib.py, line 1110, in classSetup
      self.logs += self.target_process.lognames
  AttributeError: 'VcsSim' object has no attribute 'lognames'