v/entry.S: replace sbadaddr with stval
The RISC-V Privileged ISA v1.10 uses stval instead of
sbadaddr. Although GCC can cope with sbadaddr, clang cannot. It fails
with:

  error: operand must be a valid system register name or an integer in
  the range [0, 4095]