Replace sptbr with satp throughout
The RISC-V Privileged ISA v1.10 uses satp instead of sptbr. Although
GCC can cope with sptbr, clang cannot. It fails with:

  error: operand must be a valid system register name or an integer in
  the range [0, 4095]

Modified the variable name in vm.c as well to ensure consistency and
avoid possible confusion.